<?php


/**
 * This class defines the structure of the 'City_Search' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Dec  9 13:04:54 2014
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class CitySearchTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.CitySearchTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('City_Search');
		$this->setPhpName('CitySearch');
		$this->setClassname('CitySearch');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addColumn('CITYID', 'Cityid', 'INTEGER', true, 11, 0);
		$this->addColumn('CITYNAME', 'Cityname', 'VARCHAR', false, 50, null);
		$this->addColumn('STATENAME', 'Statename', 'VARCHAR', false, 50, null);
		$this->addColumn('CITYCODE', 'Citycode', 'VARCHAR', false, 50, null);
		$this->addColumn('BROKERCITYNAME', 'Brokercityname', 'VARCHAR', false, 50, null);
		$this->addColumn('RETAILBROKERCITY', 'Retailbrokercity', 'VARCHAR', false, 250, null);
		$this->addColumn('CREATEDBY', 'Createdby', 'DOUBLE', false, null, null);
		$this->addColumn('CREATEDON', 'Createdon', 'TIMESTAMP', false, null, null);
		$this->addColumn('MODIFIEDBY', 'Modifiedby', 'DOUBLE', false, null, null);
		$this->addColumn('MODIFIEDON', 'Modifiedon', 'TIMESTAMP', false, null, null);
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // CitySearchTableMap
