<?php


/**
 * This class defines the structure of the 'sysdiagrams' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Apr  1 12:06:52 2014
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class SysdiagramsTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.SysdiagramsTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('sysdiagrams');
		$this->setPhpName('Sysdiagrams');
		$this->setClassname('Sysdiagrams');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addColumn('NAME', 'Name', 'VARCHAR', true, 160, null);
		$this->addColumn('PRINCIPAL_ID', 'PrincipalId', 'INTEGER', true, 11, null);
		$this->addPrimaryKey('DIAGRAM_ID', 'DiagramId', 'INTEGER', true, 11, null);
		$this->addColumn('VERSION', 'Version', 'INTEGER', false, 11, null);
		$this->addColumn('DEFINITION', 'Definition', 'BLOB', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // SysdiagramsTableMap
