default:
  layout: layout
  stylesheets: [layout.css,reset.css,stylesheet.css]
  javascripts: [jquery-1.9.1.js, jquery.validate.js]

ListSuccess:
  layout: layout
  stylesheets: [jquery-ui-1.10.3.custom.css,sweet-alert.css]
  javascripts: [jquery-ui-1.10.3.custom.js,searchjQuery.js,custom-jquery.js,sweet-alert.min.js]
  
QCListSuccess:
  layout: layout
  stylesheets: [jquery-ui-1.10.3.custom.css]
  javascripts: [jquery-ui-1.10.3.custom.js,searchjQuery.js,QcList.js,custom-jquery.js]
  
QCAmendmentListSuccess:
  layout: layout
  stylesheets: [jquery-ui-1.10.3.custom.css]
  javascripts: [jquery-ui-1.10.3.custom.js,searchjQuery.js,QcList.js,custom-jquery.js]
  
QCViewSuccess:
  layout: layout
  stylesheets: [jquery-ui-1.10.3.custom.css]
  
createSubmissionSuccess:
  layout: layout
  stylesheets: [jquery-ui-1.10.3.custom.css]
  javascripts: [jquery-ui-1.10.3.custom.js,comments.js, stateCityAjax.js, jquery-ui-timepicker-addon.js,jquery.formatCurrency.js]
  
editSubmissionSuccess:
  layout: layout
  stylesheets: [jquery-ui-1.10.3.custom.css]
  javascripts: [jquery-ui-1.10.3.custom.js,editSubmission.js, stateCityAjaxEdit.js, jquery-ui-timepicker-addon.js,jquery.formatCurrency.js,jquery-ui.min.js]
  
ViewSubmissionSuccess:
  layout: layout
  stylesheets: [jquery-ui-1.10.3.custom.css]
  
SubmissionSuccess:
  layout: layout
  stylesheets: [jquery-ui-1.10.3.custom.css]
  
endersomentSubmissionSuccess:
  layout: layout
  stylesheets: [jquery-ui-1.10.3.custom.css,sweet-alert.css]
  javascripts: [jquery-ui-1.10.3.custom.js,amendementCityAjax.js,amendement.js, jquery-ui-timepicker-addon.js,jquery.formatCurrency.js,sweet-alert.min.js,jquery-ui.min.js] 
  
editEndorsementSubmissionSuccess:
 layout: layout
 stylesheets: [jquery-ui-1.10.3.custom.css,sweet-alert.css]
 javascripts: [jquery-ui-1.10.3.custom.js, amendementCityAjaxEdit.js, editamendement.js, jquery-ui-timepicker-addon.js,jquery.formatCurrency.js,sweet-alert.min.js,jquery-ui.min.js]
 
editEndorsementReversalChildSuccess:
 layout: layout
 stylesheets: [jquery-ui-1.10.3.custom.css,sweet-alert.css]
 javascripts: [jquery-ui-1.10.3.custom.js, amendementCityAjaxEdit.js,editamendmentreversal.js, jquery-ui-timepicker-addon.js,jquery.formatCurrency.js,sweet-alert.min.js,jquery-ui.min.js]

viewEndersomentSubmissionSuccess:
  layout: layout
  stylesheets: [jquery-ui-1.10.3.custom.css]