<?php


/**
 * This class defines the structure of the 'Underwriter' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Apr  1 12:06:52 2014
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class UnderwriterTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.UnderwriterTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('Underwriter');
		$this->setPhpName('Underwriter');
		$this->setClassname('Underwriter');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
		$this->addColumn('NAME', 'Name', 'CLOB', false, null, null);
		$this->addColumn('SUBTYPE', 'Subtype', 'VARCHAR', false, 50, null);
		$this->addForeignKey('BRANCHID', 'Branchid', 'INTEGER', 'Branch', 'ID', false, 11, 0);
		$this->addColumn('LOBID', 'Lobid', 'INTEGER', false, 11, 0);
		$this->addForeignKey('LOBSUBTYPEID', 'Lobsubtypeid', 'INTEGER', 'LOBSubType', 'ID', false, 11, 0);
		$this->addColumn('SSMA_TIMESTAMP', 'SsmaTimestamp', 'VARCHAR', true, 8, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Branch', 'Branch', RelationMap::MANY_TO_ONE, array('BranchId' => 'Id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('Lobsubtype', 'Lobsubtype', RelationMap::MANY_TO_ONE, array('LOBSubTypeId' => 'Id', ), 'CASCADE', 'CASCADE');
    $this->addRelation('Submission', 'Submission', RelationMap::ONE_TO_MANY, array('Id' => 'UnderwriterId', ), 'RESTRICT', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // UnderwriterTableMap
