<?php

/**
 * Base class that represents a row from the 'ADDRESS_HISTORY' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Mar 19 17:19:30 2014
 *
 * @package    lib.model.om
 */
abstract class BaseAddressHistory extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AddressHistoryPeer
	 */
	protected static $peer;

	/**
	 * The value for the address_history_id field.
	 * @var        int
	 */
	protected $address_history_id;

	/**
	 * The value for the submission_history_id field.
	 * @var        int
	 */
	protected $submission_history_id;

	/**
	 * The value for the address_line1 field.
	 * @var        string
	 */
	protected $address_line1;

	/**
	 * The value for the address_line2 field.
	 * @var        string
	 */
	protected $address_line2;

	/**
	 * The value for the city field.
	 * @var        string
	 */
	protected $city;

	/**
	 * The value for the state_id field.
	 * @var        int
	 */
	protected $state_id;

	/**
	 * The value for the zip_code field.
	 * @var        string
	 */
	protected $zip_code;

	/**
	 * The value for the country field.
	 * @var        string
	 */
	protected $country;

	/**
	 * The value for the address_type field.
	 * Note: this column has a database default value of: 'mailing'
	 * @var        string
	 */
	protected $address_type;

	/**
	 * The value for the new_address_line1 field.
	 * @var        string
	 */
	protected $new_address_line1;

	/**
	 * The value for the new_address_line2 field.
	 * @var        string
	 */
	protected $new_address_line2;

	/**
	 * The value for the new_city field.
	 * @var        string
	 */
	protected $new_city;

	/**
	 * The value for the new_state_id field.
	 * @var        int
	 */
	protected $new_state_id;

	/**
	 * The value for the new_zip_code field.
	 * @var        string
	 */
	protected $new_zip_code;

	/**
	 * The value for the new_country field.
	 * @var        string
	 */
	protected $new_country;

	/**
	 * The value for the created_on field.
	 * @var        string
	 */
	protected $created_on;

	/**
	 * The value for the modified_on field.
	 * @var        string
	 */
	protected $modified_on;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'AddressHistoryPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->address_type = 'mailing';
	}

	/**
	 * Initializes internal state of BaseAddressHistory object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [address_history_id] column value.
	 * 
	 * @return     int
	 */
	public function getAddressHistoryId()
	{
		return $this->address_history_id;
	}

	/**
	 * Get the [submission_history_id] column value.
	 * 
	 * @return     int
	 */
	public function getSubmissionHistoryId()
	{
		return $this->submission_history_id;
	}

	/**
	 * Get the [address_line1] column value.
	 * 
	 * @return     string
	 */
	public function getAddressLine1()
	{
		return $this->address_line1;
	}

	/**
	 * Get the [address_line2] column value.
	 * 
	 * @return     string
	 */
	public function getAddressLine2()
	{
		return $this->address_line2;
	}

	/**
	 * Get the [city] column value.
	 * 
	 * @return     string
	 */
	public function getCity()
	{
		return $this->city;
	}

	/**
	 * Get the [state_id] column value.
	 * 
	 * @return     int
	 */
	public function getStateId()
	{
		return $this->state_id;
	}

	/**
	 * Get the [zip_code] column value.
	 * 
	 * @return     string
	 */
	public function getZipCode()
	{
		return $this->zip_code;
	}

	/**
	 * Get the [country] column value.
	 * 
	 * @return     string
	 */
	public function getCountry()
	{
		return $this->country;
	}

	/**
	 * Get the [address_type] column value.
	 * 
	 * @return     string
	 */
	public function getAddressType()
	{
		return $this->address_type;
	}

	/**
	 * Get the [new_address_line1] column value.
	 * 
	 * @return     string
	 */
	public function getNewAddressLine1()
	{
		return $this->new_address_line1;
	}

	/**
	 * Get the [new_address_line2] column value.
	 * 
	 * @return     string
	 */
	public function getNewAddressLine2()
	{
		return $this->new_address_line2;
	}

	/**
	 * Get the [new_city] column value.
	 * 
	 * @return     string
	 */
	public function getNewCity()
	{
		return $this->new_city;
	}

	/**
	 * Get the [new_state_id] column value.
	 * 
	 * @return     int
	 */
	public function getNewStateId()
	{
		return $this->new_state_id;
	}

	/**
	 * Get the [new_zip_code] column value.
	 * 
	 * @return     string
	 */
	public function getNewZipCode()
	{
		return $this->new_zip_code;
	}

	/**
	 * Get the [new_country] column value.
	 * 
	 * @return     string
	 */
	public function getNewCountry()
	{
		return $this->new_country;
	}

	/**
	 * Get the [optionally formatted] temporal [created_on] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedOn($format = 'Y-m-d H:i:s')
	{
		if ($this->created_on === null) {
			return null;
		}


		if ($this->created_on === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_on);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_on, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [modified_on] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getModifiedOn($format = 'Y-m-d H:i:s')
	{
		if ($this->modified_on === null) {
			return null;
		}


		if ($this->modified_on === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->modified_on);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->modified_on, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [address_history_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setAddressHistoryId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->address_history_id !== $v) {
			$this->address_history_id = $v;
			$this->modifiedColumns[] = AddressHistoryPeer::ADDRESS_HISTORY_ID;
		}

		return $this;
	} // setAddressHistoryId()

	/**
	 * Set the value of [submission_history_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setSubmissionHistoryId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->submission_history_id !== $v) {
			$this->submission_history_id = $v;
			$this->modifiedColumns[] = AddressHistoryPeer::SUBMISSION_HISTORY_ID;
		}

		return $this;
	} // setSubmissionHistoryId()

	/**
	 * Set the value of [address_line1] column.
	 * 
	 * @param      string $v new value
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setAddressLine1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->address_line1 !== $v) {
			$this->address_line1 = $v;
			$this->modifiedColumns[] = AddressHistoryPeer::ADDRESS_LINE1;
		}

		return $this;
	} // setAddressLine1()

	/**
	 * Set the value of [address_line2] column.
	 * 
	 * @param      string $v new value
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setAddressLine2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->address_line2 !== $v) {
			$this->address_line2 = $v;
			$this->modifiedColumns[] = AddressHistoryPeer::ADDRESS_LINE2;
		}

		return $this;
	} // setAddressLine2()

	/**
	 * Set the value of [city] column.
	 * 
	 * @param      string $v new value
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setCity($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->city !== $v) {
			$this->city = $v;
			$this->modifiedColumns[] = AddressHistoryPeer::CITY;
		}

		return $this;
	} // setCity()

	/**
	 * Set the value of [state_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setStateId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->state_id !== $v) {
			$this->state_id = $v;
			$this->modifiedColumns[] = AddressHistoryPeer::STATE_ID;
		}

		return $this;
	} // setStateId()

	/**
	 * Set the value of [zip_code] column.
	 * 
	 * @param      string $v new value
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setZipCode($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->zip_code !== $v) {
			$this->zip_code = $v;
			$this->modifiedColumns[] = AddressHistoryPeer::ZIP_CODE;
		}

		return $this;
	} // setZipCode()

	/**
	 * Set the value of [country] column.
	 * 
	 * @param      string $v new value
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setCountry($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->country !== $v) {
			$this->country = $v;
			$this->modifiedColumns[] = AddressHistoryPeer::COUNTRY;
		}

		return $this;
	} // setCountry()

	/**
	 * Set the value of [address_type] column.
	 * 
	 * @param      string $v new value
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setAddressType($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->address_type !== $v || $this->isNew()) {
			$this->address_type = $v;
			$this->modifiedColumns[] = AddressHistoryPeer::ADDRESS_TYPE;
		}

		return $this;
	} // setAddressType()

	/**
	 * Set the value of [new_address_line1] column.
	 * 
	 * @param      string $v new value
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setNewAddressLine1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->new_address_line1 !== $v) {
			$this->new_address_line1 = $v;
			$this->modifiedColumns[] = AddressHistoryPeer::NEW_ADDRESS_LINE1;
		}

		return $this;
	} // setNewAddressLine1()

	/**
	 * Set the value of [new_address_line2] column.
	 * 
	 * @param      string $v new value
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setNewAddressLine2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->new_address_line2 !== $v) {
			$this->new_address_line2 = $v;
			$this->modifiedColumns[] = AddressHistoryPeer::NEW_ADDRESS_LINE2;
		}

		return $this;
	} // setNewAddressLine2()

	/**
	 * Set the value of [new_city] column.
	 * 
	 * @param      string $v new value
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setNewCity($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->new_city !== $v) {
			$this->new_city = $v;
			$this->modifiedColumns[] = AddressHistoryPeer::NEW_CITY;
		}

		return $this;
	} // setNewCity()

	/**
	 * Set the value of [new_state_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setNewStateId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->new_state_id !== $v) {
			$this->new_state_id = $v;
			$this->modifiedColumns[] = AddressHistoryPeer::NEW_STATE_ID;
		}

		return $this;
	} // setNewStateId()

	/**
	 * Set the value of [new_zip_code] column.
	 * 
	 * @param      string $v new value
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setNewZipCode($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->new_zip_code !== $v) {
			$this->new_zip_code = $v;
			$this->modifiedColumns[] = AddressHistoryPeer::NEW_ZIP_CODE;
		}

		return $this;
	} // setNewZipCode()

	/**
	 * Set the value of [new_country] column.
	 * 
	 * @param      string $v new value
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setNewCountry($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->new_country !== $v) {
			$this->new_country = $v;
			$this->modifiedColumns[] = AddressHistoryPeer::NEW_COUNTRY;
		}

		return $this;
	} // setNewCountry()

	/**
	 * Sets the value of [created_on] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setCreatedOn($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_on !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_on !== null && $tmpDt = new DateTime($this->created_on)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_on = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AddressHistoryPeer::CREATED_ON;
			}
		} // if either are not null

		return $this;
	} // setCreatedOn()

	/**
	 * Sets the value of [modified_on] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AddressHistory The current object (for fluent API support)
	 */
	public function setModifiedOn($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->modified_on !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->modified_on !== null && $tmpDt = new DateTime($this->modified_on)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->modified_on = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AddressHistoryPeer::MODIFIED_ON;
			}
		} // if either are not null

		return $this;
	} // setModifiedOn()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->address_type !== 'mailing') {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->address_history_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->submission_history_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->address_line1 = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->address_line2 = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->city = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->state_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->zip_code = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->country = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->address_type = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->new_address_line1 = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->new_address_line2 = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->new_city = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->new_state_id = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->new_zip_code = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->new_country = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->created_on = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->modified_on = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 17; // 17 = AddressHistoryPeer::NUM_COLUMNS - AddressHistoryPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating AddressHistory object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AddressHistoryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AddressHistoryPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AddressHistoryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAddressHistory:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				AddressHistoryPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAddressHistory:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AddressHistoryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAddressHistory:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAddressHistory:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				AddressHistoryPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AddressHistoryPeer::ADDRESS_HISTORY_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AddressHistoryPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setAddressHistoryId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AddressHistoryPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = AddressHistoryPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AddressHistoryPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getAddressHistoryId();
				break;
			case 1:
				return $this->getSubmissionHistoryId();
				break;
			case 2:
				return $this->getAddressLine1();
				break;
			case 3:
				return $this->getAddressLine2();
				break;
			case 4:
				return $this->getCity();
				break;
			case 5:
				return $this->getStateId();
				break;
			case 6:
				return $this->getZipCode();
				break;
			case 7:
				return $this->getCountry();
				break;
			case 8:
				return $this->getAddressType();
				break;
			case 9:
				return $this->getNewAddressLine1();
				break;
			case 10:
				return $this->getNewAddressLine2();
				break;
			case 11:
				return $this->getNewCity();
				break;
			case 12:
				return $this->getNewStateId();
				break;
			case 13:
				return $this->getNewZipCode();
				break;
			case 14:
				return $this->getNewCountry();
				break;
			case 15:
				return $this->getCreatedOn();
				break;
			case 16:
				return $this->getModifiedOn();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AddressHistoryPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getAddressHistoryId(),
			$keys[1] => $this->getSubmissionHistoryId(),
			$keys[2] => $this->getAddressLine1(),
			$keys[3] => $this->getAddressLine2(),
			$keys[4] => $this->getCity(),
			$keys[5] => $this->getStateId(),
			$keys[6] => $this->getZipCode(),
			$keys[7] => $this->getCountry(),
			$keys[8] => $this->getAddressType(),
			$keys[9] => $this->getNewAddressLine1(),
			$keys[10] => $this->getNewAddressLine2(),
			$keys[11] => $this->getNewCity(),
			$keys[12] => $this->getNewStateId(),
			$keys[13] => $this->getNewZipCode(),
			$keys[14] => $this->getNewCountry(),
			$keys[15] => $this->getCreatedOn(),
			$keys[16] => $this->getModifiedOn(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AddressHistoryPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setAddressHistoryId($value);
				break;
			case 1:
				$this->setSubmissionHistoryId($value);
				break;
			case 2:
				$this->setAddressLine1($value);
				break;
			case 3:
				$this->setAddressLine2($value);
				break;
			case 4:
				$this->setCity($value);
				break;
			case 5:
				$this->setStateId($value);
				break;
			case 6:
				$this->setZipCode($value);
				break;
			case 7:
				$this->setCountry($value);
				break;
			case 8:
				$this->setAddressType($value);
				break;
			case 9:
				$this->setNewAddressLine1($value);
				break;
			case 10:
				$this->setNewAddressLine2($value);
				break;
			case 11:
				$this->setNewCity($value);
				break;
			case 12:
				$this->setNewStateId($value);
				break;
			case 13:
				$this->setNewZipCode($value);
				break;
			case 14:
				$this->setNewCountry($value);
				break;
			case 15:
				$this->setCreatedOn($value);
				break;
			case 16:
				$this->setModifiedOn($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AddressHistoryPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setAddressHistoryId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setSubmissionHistoryId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setAddressLine1($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setAddressLine2($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setCity($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setStateId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setZipCode($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setCountry($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setAddressType($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setNewAddressLine1($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setNewAddressLine2($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setNewCity($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setNewStateId($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setNewZipCode($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setNewCountry($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setCreatedOn($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setModifiedOn($arr[$keys[16]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AddressHistoryPeer::DATABASE_NAME);

		if ($this->isColumnModified(AddressHistoryPeer::ADDRESS_HISTORY_ID)) $criteria->add(AddressHistoryPeer::ADDRESS_HISTORY_ID, $this->address_history_id);
		if ($this->isColumnModified(AddressHistoryPeer::SUBMISSION_HISTORY_ID)) $criteria->add(AddressHistoryPeer::SUBMISSION_HISTORY_ID, $this->submission_history_id);
		if ($this->isColumnModified(AddressHistoryPeer::ADDRESS_LINE1)) $criteria->add(AddressHistoryPeer::ADDRESS_LINE1, $this->address_line1);
		if ($this->isColumnModified(AddressHistoryPeer::ADDRESS_LINE2)) $criteria->add(AddressHistoryPeer::ADDRESS_LINE2, $this->address_line2);
		if ($this->isColumnModified(AddressHistoryPeer::CITY)) $criteria->add(AddressHistoryPeer::CITY, $this->city);
		if ($this->isColumnModified(AddressHistoryPeer::STATE_ID)) $criteria->add(AddressHistoryPeer::STATE_ID, $this->state_id);
		if ($this->isColumnModified(AddressHistoryPeer::ZIP_CODE)) $criteria->add(AddressHistoryPeer::ZIP_CODE, $this->zip_code);
		if ($this->isColumnModified(AddressHistoryPeer::COUNTRY)) $criteria->add(AddressHistoryPeer::COUNTRY, $this->country);
		if ($this->isColumnModified(AddressHistoryPeer::ADDRESS_TYPE)) $criteria->add(AddressHistoryPeer::ADDRESS_TYPE, $this->address_type);
		if ($this->isColumnModified(AddressHistoryPeer::NEW_ADDRESS_LINE1)) $criteria->add(AddressHistoryPeer::NEW_ADDRESS_LINE1, $this->new_address_line1);
		if ($this->isColumnModified(AddressHistoryPeer::NEW_ADDRESS_LINE2)) $criteria->add(AddressHistoryPeer::NEW_ADDRESS_LINE2, $this->new_address_line2);
		if ($this->isColumnModified(AddressHistoryPeer::NEW_CITY)) $criteria->add(AddressHistoryPeer::NEW_CITY, $this->new_city);
		if ($this->isColumnModified(AddressHistoryPeer::NEW_STATE_ID)) $criteria->add(AddressHistoryPeer::NEW_STATE_ID, $this->new_state_id);
		if ($this->isColumnModified(AddressHistoryPeer::NEW_ZIP_CODE)) $criteria->add(AddressHistoryPeer::NEW_ZIP_CODE, $this->new_zip_code);
		if ($this->isColumnModified(AddressHistoryPeer::NEW_COUNTRY)) $criteria->add(AddressHistoryPeer::NEW_COUNTRY, $this->new_country);
		if ($this->isColumnModified(AddressHistoryPeer::CREATED_ON)) $criteria->add(AddressHistoryPeer::CREATED_ON, $this->created_on);
		if ($this->isColumnModified(AddressHistoryPeer::MODIFIED_ON)) $criteria->add(AddressHistoryPeer::MODIFIED_ON, $this->modified_on);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AddressHistoryPeer::DATABASE_NAME);

		$criteria->add(AddressHistoryPeer::ADDRESS_HISTORY_ID, $this->address_history_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getAddressHistoryId();
	}

	/**
	 * Generic method to set the primary key (address_history_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setAddressHistoryId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of AddressHistory (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setSubmissionHistoryId($this->submission_history_id);

		$copyObj->setAddressLine1($this->address_line1);

		$copyObj->setAddressLine2($this->address_line2);

		$copyObj->setCity($this->city);

		$copyObj->setStateId($this->state_id);

		$copyObj->setZipCode($this->zip_code);

		$copyObj->setCountry($this->country);

		$copyObj->setAddressType($this->address_type);

		$copyObj->setNewAddressLine1($this->new_address_line1);

		$copyObj->setNewAddressLine2($this->new_address_line2);

		$copyObj->setNewCity($this->new_city);

		$copyObj->setNewStateId($this->new_state_id);

		$copyObj->setNewZipCode($this->new_zip_code);

		$copyObj->setNewCountry($this->new_country);

		$copyObj->setCreatedOn($this->created_on);

		$copyObj->setModifiedOn($this->modified_on);


		$copyObj->setNew(true);

		$copyObj->setAddressHistoryId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     AddressHistory Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AddressHistoryPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AddressHistoryPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseAddressHistory:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseAddressHistory::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseAddressHistory
