<?php


/**
 * Skeleton subclass for performing query and update operations on the 'Branch' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Apr  1 12:06:49 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class BranchPeer extends BaseBranchPeer {

} // BranchPeer
