<?php


/**
 * Skeleton subclass for representing a row from the 'Broker_Search' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Jul 28 10:47:08 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class BrokerSearch extends BaseBrokerSearch {

} // BrokerSearch