<?php


/**
 * Skeleton subclass for performing query and update operations on the 'BusinessDependentDetail' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Apr  1 12:06:50 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class BusinessdependentdetailPeer extends BaseBusinessdependentdetailPeer {

} // BusinessdependentdetailPeer
