ALTER TABLE `SUBMISSION` ADD COLUMN `REASON_CODE` ENUM('D1','D2','D3','D4','D5','D6','L1','L2','L3','L4','L5','L6','NA'),
ADD COLUMN `NAIC_CODE` INTEGER(6),
ADD COLUMN `SIC_CODE` INTEGER(6),
ADD COLUMN `NAIC_TITLE` VARCHAR(164);

ALTER TABLE `SUBMISSION_HISTORY` ADD COLUMN `REASON_CODE` ENUM('D1','D2','D3','D4','D5','D6','L1','L2','L3','L4','L5','L6','NA'),
ADD COLUMN `NAIC_CODE` INTEGER(6),
ADD COLUMN `SIC_CODE` INTEGER(6),
ADD COLUMN `NAIC_TITLE` VARCHAR(164),
ADD COLUMN `NEW_REASON_CODE` ENUM('D1','D2','D3','D4','D5','D6','L1','L2','L3','L4','L5','L6','NA'),
ADD COLUMN `NEW_NAIC_CODE` INTEGER(6),
ADD COLUMN `NEW_SIC_CODE` INTEGER(6),
ADD COLUMN `NEW_NAIC_TITLE` VARCHAR(164);
