<?php


/**
 * Skeleton subclass for performing query and update operations on the 'Submission' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 14 10:26:50 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class SubmissionPeer extends BaseSubmissionPeer {

} // SubmissionPeer
